apiVersion: v1
kind: Service
metadata:
  name: rime-config-engine
  namespace: rime-config
spec:
  selector:
    app: rime-config-engine
  ports:
    - name: http
      port: 80
      targetPort: http
